mylist/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls',namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/	
    url(r'^(?P<solver_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<solver_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/registrar/
    url(r'^registrar/$',views.registrar, name='registrar'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Solvers(models.Model):
    Username = models.CharField(max_length=200)
    password = models.CharField(max_length=50)
    fechaRegistro = models.DateTimeField('fecha de creacion')
    Email = models.EmailField(max_length=70)
    Name = models.CharField(max_length=200)
    Age = models.IntegerField(default=0)

    dato3 = 'Sheila Ricalde'
    def __str__(self):
    	return self.Username
class Skill(models.Model):
    username = models.ForeignKey(Solvers)
    skill = models.CharField(max_length=200)
    def __str__(self):
    	return self.skill

polls/forms.py
from django.forms import ModelForm
from django import forms
from polls.models import Solvers,Skill

class Usuarioform(forms.Form):
    class Meta:
        model = Solvers

polls/views.py
from django.shortcuts import get_object_or_404, render,loader,RequestContext,render_to_response

# Create your views here.
from django.http import HttpResponse,Http404, HttpResponseRedirect
from django.core.urlresolvers import reverse

from .models import Solvers,Skill
from .forms import UsuarioForm


def index(request):
    latest_solvers_list = Solvers.objects.order_by('-fechaRegistro')[:5]
    context = {'latest_solvers_list' : latest_solvers_list}
    return render(request,'polls/index.html',context)

def detail(request, solver_id):
    try:
        solver = Solvers.objects.get(pk=solver_id)
    except Solvers.DoesNotExist:
        raise Http404("Solver does not exist")
    return render (request, 'polls/detail.html',{'solver':solver})

def results(request,solver_id):
    solver = get_object_or_404(Solvers,pk=solver_id)
    return render(request,'polls/results.html', {'solver': solver})

def registrar(request):
    if request.method =='POST':
        formSolver = UsuarioForm(request.POST)
        if formSolver.is_valid():
            formSolver.save()
            return HttpResponseRedirect('registrar.html')
    else:
        formSolver = Usuarioform()
    return render_to_response('polls/registrar.html',{'formSolver':formSolver},context_instance=RequestContext(request))  

polls/templates/polls/detail.html
<h1>{{solver.Username}}</h1>
{% if error_message %} <p> <strong> {{ error_message }}</strong></p>{% endif %}
<form action="{% url 'polls:vote' solver.id %}" method="post">
{% csrf_token %}
<input type="text" name="skill"><br>
<input type="submit" value="vote">
</form>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ursolver</title>
</head>
<body>
{% if latest_solvers_list %}
    <ul>
    {% for solver in latest_solvers_list %}
        <li><a href="{% url 'polls:results' solver.id %}">{{ solver.Username }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/registrar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>Registrar Usuario</title>
</head>
<body>
    <form id='' method='post' action="{% url 'polls:registrar' %}">
        {% csrf_token %}
        {{form.as_table}}
        <input type="submit" value"Registrar">
    </form>
    

</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Ursolver - Solvers </title>
</head>
<body>
	<h1>{{ solver.Username }}</h1>
	<ul>
		<li>{{ solver.Email}}</li>
		<li>{{ solver.Name}}</li>
		<li>{{ solver.Age}}</li>
		<li>{{ solver.password}}</li>
		<li>{{ solver.fechaRegistro}}</li>
		<li>Skills:</li>
		<ul>	
			{% for skill in solver.skill_set.all %}
		    <li>{{ skill.skill }}</li>
		{% endfor %}	
		</ul>
	</ul>



</body>
</html>